version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    networks:
      - app-network

  api:
    image: my-dotnet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    environment:
      - DefaultConnection=Server=sql,1433;Database=DatingDB;User Id=SA;Password=Password@1;TrustServerCertificate=True

networks:
  app-network:
    driver: bridge