version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: "PaakabooDB"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: 'Password@1'
      MYSQL_ROOT_PASSWORD: "Password@1"
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    image: my-dotnet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    environment:
      - ConnectionStrings_DefaultConnection=server=mysql;port=3306;database=PaakabooDB;user=root;password=Password@1;
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge